## 設定とモデルのロード
設定値（モデル・層・成果物の場所）は `run.py` の先頭にまとめてある。変える場合はそちらを編集する。

In [ ]:
import run   # backend/ に移動し、sys.path を設定する
from run import (MODEL_ID, RESEARCH_MODEL_KEY, TARGET_LAYER, ASSETS_ROOT,
                 build_manager, start_voicevox, start_server)
from app.core.llm_engine import LLMEngine

print("model :", MODEL_ID)
print("layer :", TARGET_LAYER, "(hidden_states のインデックス)")
print("assets:", ASSETS_ROOT)

model : tokyotech-llm/Llama-3.1-Swallow-8B-Instruct-v0.5
layer : 21 (hidden_states のインデックス)
assets: /workspace/app_labGuide_v2/backend/data/processed/steering_assets

In [ ]:
# 量子化しない（活性化の値が変わり、成果物の avg_norm・α上限と対応しなくなる）
engine = LLMEngine(model_id=MODEL_ID, quantization_8bit=False)

Loading model: tokyotech-llm/Llama-3.1-Swallow-8B-Instruct-v0.5...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Model loaded successfully.

## 成果物の検証

### 確認

In [ ]:
import numpy as np
d = np.load("data/processed/steering_assets/emotion_probe/probe_layer21.npz", allow_pickle=True)
print(d["dataset"], float(d["test_accuracy"]))    # synthetic_resp 0.8827... なら同梱品

synthetic_resp 0.8827948910593538

In [ ]:
# !touch scripts/__init__.py
# どこかに __init__.py 付きの scripts があるとそちらが先に見つかってしまってエラーになるのでinitを作成、中身は空

### A ~ Fの検証

In [ ]:
## 出力は/tmp
# A. 合成データ6,651文を生成条件で読み、ベクトルとプローブを作り直す
from scripts.build_assets import build_all
build_all(engine, steps=["activations", "vectors", "probe"], assets_root="/tmp/rebuilt")

[extract_activations] model=llama-3.1-swallow-8b-instruct-v0.5 position=response_mean layers=[21]
[load_synthetic] joy          : 739件 (level>=1)
[load_synthetic] sadness      : 739件 (level>=1)
[load_synthetic] anticipation : 739件 (level>=1)
[load_synthetic] surprise     : 739件 (level>=1)
[load_synthetic] anger        : 739件 (level>=1)
[load_synthetic] fear         : 739件 (level>=1)
[load_synthetic] disgust      : 739件 (level>=1)
[load_synthetic] trust        : 739件 (level>=1)

[extract_activations] 'anger' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'anticipation' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'disgust' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'fear' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'joy' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'sadness' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'surprise' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47

[extract_activations] 'trust' を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47
[extract_activations] 感情文を保存 -> /workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/synthetic_resp (計5912件)
[load_neutral] 739件読み込み: /workspace/app_labGuide_v2/backend/data/raw/steering/synthetic/neutral_spoken_739.jsonl

[extract_activations] 中立文を抽出中... (739件)
[extract@response]   batch 10/47
[extract@response]   batch 20/47
[extract@response]   batch 30/47
[extract@response]   batch 40/47
[extract@response]   batch 47/47
[extract_activations] 中立文を保存 -> /workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/neutral_resp (739件)

============================================================
[steering_vectors] layer=21
============================================================
[steering_vectors] 感情ごとの件数: {'anger': 739, 'anticipation': 739, 'disgust': 739, 'fear': 739, 'joy': 739, 'sadness': 739, 'surprise': 739, 'trust': 739} / 中立: 739
[compute_neutral_pca] r=14 主成分で累積寄与率 50.0% (閾値 50%)
[compute_caa_vectors] anger        : ||diff||=1.7789 -> ||v||=1.6732 (中立成分除去で 5.9% 減衰)
[compute_caa_vectors] anticipation : ||diff||=1.5033 -> ||v||=1.3780 (中立成分除去で 8.3% 減衰)
[compute_caa_vectors] disgust      : ||diff||=1.3592 -> ||v||=1.2814 (中立成分除去で 5.7% 減衰)
[compute_caa_vectors] fear         : ||diff||=1.4190 -> ||v||=1.2431 (中立成分除去で 12.4% 減衰)
[compute_caa_vectors] joy          : ||diff||=1.4929 -> ||v||=1.3698 (中立成分除去で 8.2% 減衰)
[compute_caa_vectors] sadness      : ||diff||=1.4588 -> ||v||=1.3464 (中立成分除去で 7.7% 減衰)
[compute_caa_vectors] surprise     : ||diff||=2.2377 -> ||v||=2.0758 (中立成分除去で 7.2% 減衰)
[compute_caa_vectors] trust        : ||diff||=1.9050 -> ||v||=1.7398 (中立成分除去で 8.7% 減衰)
[steering_vectors] avg_norm(layer=21) = 10.6057  ※αのスケール基準
[SteeringVectorSet.save] -> /tmp/rebuilt/steering_vectors/llama-3.1-swallow-8b-instruct-v0.5/layer_21
[probe] 中立クラスを追加: 739件 (/workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/neutral_resp/layer_21.npy)
[probe] llama-3.1-swallow-8b-instruct-v0.5 layer=21 dataset=synthetic_resp
[probe] X=(6651, 4096)  クラス分布={'anger': 739, 'anticipation': 739, 'disgust': 739, 'fear': 739, 'joy': 739, 'neutral': 739, 'sadness': 739, 'surprise': 739, 'trust': 739}
[probe] train_accuracy=0.9934  test_accuracy=0.8828

[probe] 混同行列（行=正解, 列=予測）:
              anger  antici  disgus    fear     joy  neutra  sadnes  surpri   trust
  anger         120       2      17       5       0       0       2       2       0   (0.81)
  anticipation      3     129       2       2       8       0       1       0       3   (0.87)
  disgust        15       0     120       4       1       0       6       0       2   (0.81)
  fear            1       1       1     126       1       0       5      12       1   (0.85)
  joy             0       3       0       1     129       1       2       1      11   (0.87)
  neutral         0       0       0       1       0     147       0       0       0   (0.99)
  sadness         1       1       3       5       2       0     135       0       1   (0.91)
  surprise        1       1       0       3       3       0       1     135       3   (0.92)
  trust           1       2       1       0       6       0       3       1     134   (0.91)

[probe] 保存 -> /tmp/rebuilt/emotion_probe/probe_layer21.npz  (W=(9, 4096), classes=['anger', 'anticipation', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise', 'trust'])

[build_assets] 完了: ['activations', 'vectors', 'probe']（177秒）
[build_assets] ★ベクトルを作り直したので、α上限（chatbot_alpha_cap.json）が今のベクトルに対して妥当かは保証されません。会話で壊れないか必ず確認してください。

{'activations': {'dataset': 'synthetic_resp',
  'neutral_dir_name': 'neutral_resp',
  'layers': [21]},
 'vectors': ['/tmp/rebuilt/steering_vectors/llama-3.1-swallow-8b-instruct-v0.5/layer_21'],
 'probe': {'path': '/tmp/rebuilt/emotion_probe/probe_layer21.npz',
  'train_accuracy': 0.993421052631579,
  'test_accuracy': 0.8827948910593538,
  'classes': ['anger',
   'anticipation',
   'disgust',
   'fear',
   'joy',
   'neutral',
   'sadness',
   'surprise',
   'trust']}}

In [ ]:
# B. 同じ6,651文を理解条件で読み、プローブだけ作る
build_all(engine, steps=["activations", "probe"], position="prompt_last",
          assets_root="/tmp/rebuilt_pl")

[extract_activations] model=llama-3.1-swallow-8b-instruct-v0.5 position=prompt_last layers=[21]
[load_synthetic] joy          : 739件 (level>=1)
[load_synthetic] sadness      : 739件 (level>=1)
[load_synthetic] anticipation : 739件 (level>=1)
[load_synthetic] surprise     : 739件 (level>=1)
[load_synthetic] anger        : 739件 (level>=1)
[load_synthetic] fear         : 739件 (level>=1)
[load_synthetic] disgust      : 739件 (level>=1)
[load_synthetic] trust        : 739件 (level>=1)

[extract_activations] 'anger' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

あー、またこれ着なきゃいけないのか。<|eot_id|><|start_header_id|>

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'anticipation' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

かぼちゃの煮物、今日ならあんな風に仕上げられるかな。<|eot_id|><|start_hea

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'disgust' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

……まあ、とりあえずこれくらいでいいかな。<|eot_id|><|start_header_i

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'fear' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

0.1秒だけ、指が止まった気がする。<|eot_id|><|start_header_id|>

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'joy' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

やれっと、なんだかいい感じに整った。<|eot_id|><|start_header_id|>

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'sadness' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

あ、またこのバス、ちょっと遅れてるんだ。<|eot_id|><|start_header_id

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'surprise' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

あ、ちょっとだけ、変わってるかも。<|eot_id|><|start_header_id|>a

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み

[extract_activations] 'trust' を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

あ、うん。それなら、なんとかなりそうだね。<|eot_id|><|start_header_i

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み
[extract_activations] 感情文を保存 -> /workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/synthetic_promptlast (計5912件)
[load_neutral] 739件読み込み: /workspace/app_labGuide_v2/backend/data/raw/steering/synthetic/neutral_spoken_739.jsonl

[extract_activations] 中立文を抽出中... (739件)
[extract_activations] 入力例:
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

あなたは誠実で優秀な日本人のアシスタントです。<|eot_id|><|begin_of_text|><|start_header_id|>user<|end_header_id|>

さっきの会議の資料の3ページ目には、予算の項目が記載されているはずだよ。<|eot_id|><

[extract_activations]   batch 10/47 処理済み
[extract_activations]   batch 20/47 処理済み
[extract_activations]   batch 30/47 処理済み
[extract_activations]   batch 40/47 処理済み
[extract_activations]   batch 47/47 処理済み
[extract_activations] 中立文を保存 -> /workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/neutral (739件)
[probe] 中立クラスを追加: 739件 (/workspace/app_labGuide_v2/backend/data/processed/activations/llama-3.1-swallow-8b-instruct-v0.5/neutral/layer_21.npy)
[probe] llama-3.1-swallow-8b-instruct-v0.5 layer=21 dataset=synthetic_promptlast
[probe] X=(6651, 4096)  クラス分布={'anger': 739, 'anticipation': 739, 'disgust': 739, 'fear': 739, 'joy': 739, 'neutral': 739, 'sadness': 739, 'surprise': 739, 'trust': 739}
[probe] train_accuracy=0.9925  test_accuracy=0.8708

[probe] 混同行列（行=正解, 列=予測）:
              anger  antici  disgus    fear     joy  neutra  sadnes  surpri   trust
  anger         123       1      13       4       1       0       3       3       0   (0.83)
  anticipation      2     126       2       1      10       0       1       1       5   (0.85)
  disgust        18       0     119       4       0       0       5       0       2   (0.80)
  fear            1       2       0     121       1       0       6      16       1   (0.82)
  joy             0       7       0       0     130       0       2       0       9   (0.88)
  neutral         0       0       0       1       0     147       0       0       0   (0.99)
  sadness         1       1       3       8       1       0     128       2       4   (0.86)
  surprise        1       0       0       5       5       0       2     131       3   (0.89)
  trust           0       2       0       0      10       0       1       1     134   (0.91)

[probe] 保存 -> /tmp/rebuilt_pl/emotion_probe/probe_layer21.npz  (W=(9, 4096), classes=['anger', 'anticipation', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise', 'trust'])

[build_assets] 完了: ['activations', 'probe']（182秒）

{'activations': {'dataset': 'synthetic_promptlast',
  'neutral_dir_name': 'neutral',
  'layers': [21]},
 'probe': {'path': '/tmp/rebuilt_pl/emotion_probe/probe_layer21.npz',
  'train_accuracy': 0.9924812030075187,
  'test_accuracy': 0.8707738542449286,
  'classes': ['anger',
   'anticipation',
   'disgust',
   'fear',
   'joy',
   'neutral',
   'sadness',
   'surprise',
   'trust']}}

In [ ]:
# C. Aで作ったベクトルを同梱品と比べる（再現確認）
from scripts.evaluate_probes import evaluate_probes, compare_assets
compare_assets("data/processed/steering_assets", "/tmp/rebuilt")
# 最後の行に 最小コサイン = 0.99以上 → 移植は正しい と出れば合格

[compare] 同梱: data/processed/steering_assets
[compare] 再生成: /tmp/rebuilt

感情                  コサイン       ノルム(同梱)        ノルム(再生成)
anger             1.0000         1.673           1.673
anticipation      1.0000         1.378           1.378
disgust           1.0000         1.281           1.281
fear              1.0000         1.243           1.243
joy               1.0000         1.370           1.370
sadness           1.0000         1.346           1.346
surprise          1.0000         2.075           2.076
trust             1.0000         1.739           1.740

項目                            同梱         再生成
avg_norm                 10.6073     10.6057
PCA 成分数                       14          14

[compare] 最小コサイン = 1.0000 → 移植は正しい

{'cosine': {'anger': 0.9999947883395752,
  'anticipation': 0.9999948566002319,
  'disgust': 0.9999949676234637,
  'fear': 0.9999917823035472,
  'joy': 0.999990261051583,
  'sadness': 0.9999943107676014,
  'surprise': 0.9999933871148723,
  'trust': 0.9999957132521001},
 'min_cosine': 0.999990261051583,
 'verdict': '移植は正しい'}

In [ ]:
# D. 3つのプローブで評価セット46文を判定し、比べる
evaluate_probes(engine, {
    "同梱（生成条件）": "data/processed/steering_assets/emotion_probe/probe_layer21.npz",
    "再生成（生成条件）": "/tmp/rebuilt/emotion_probe/probe_layer21.npz",
    "理解条件": "/tmp/rebuilt_pl/emotion_probe/probe_layer21.npz",
})

[eval] 評価セット 46件 読み込み: /workspace/app_labGuide_v2/backend/data/eval/probe_eval_set.jsonl
[eval] ラベルごとの件数: {'anger': 5, 'anticipation': 5, 'disgust': 5, 'fear': 5, 'joy': 5, 'neutral': 6, 'sadness': 5, 'surprise': 5, 'trust': 5}

======================================================================
[eval] 同梱（生成条件）: data/processed/steering_assets/emotion_probe/probe_layer21.npz
======================================================================
[EmotionProbe] data/processed/steering_assets/emotion_probe/probe_layer21.npz を読み込みました (layer=21, dataset=synthetic_resp, position=response_mean, test_acc=0.883, classes=9)
[eval] ラベルごとの正解数: anger 5/5, anticipation 4/5, disgust 1/5, fear 3/5, joy 3/5, neutral 3/6, sadness 4/5, surprise 2/5, trust 5/5

======================================================================
[eval] 再生成（生成条件）: /tmp/rebuilt/emotion_probe/probe_layer21.npz
======================================================================
[EmotionProbe] /tmp/rebuilt/emotion_probe/probe_layer21.npz を読み込みました (layer=21, dataset=synthetic_resp, position=response_mean, test_acc=0.883, classes=9)
[eval] ラベルごとの正解数: anger 5/5, anticipation 4/5, disgust 1/5, fear 3/5, joy 4/5, neutral 3/6, sadness 4/5, surprise 2/5, trust 5/5

======================================================================
[eval] 理解条件: /tmp/rebuilt_pl/emotion_probe/probe_layer21.npz
======================================================================
[EmotionProbe] /tmp/rebuilt_pl/emotion_probe/probe_layer21.npz を読み込みました (layer=21, dataset=synthetic_promptlast, position=prompt_last, test_acc=0.871, classes=9)
[eval] ラベルごとの正解数: anger 5/5, anticipation 4/5, disgust 2/5, fear 4/5, joy 4/5, neutral 1/6, sadness 5/5, surprise 4/5, trust 5/5

======================================================================
[eval] 全体の比較（評価セット 46件）
======================================================================
                              全体     感情文     中立文     中立誤爆     正解確率   合成test
同梱（生成条件）                   0.652   0.675   0.500    0.500    0.630    0.883
再生成（生成条件）                  0.674   0.700   0.500    0.500    0.629    0.883
理解条件                       0.739   0.825   0.167    0.833    0.687    0.871
  全体/感情文/中立文 : 正解率（高いほど良い）
  中立誤爆           : 中立の文を感情ありと判定した割合（低いほど良い）
  正解確率           : 正解ラベルに付いた確率の平均（高いほど自信を持って当たっている）
  合成test           : 学習時の合成データでの test acc（参考）

[eval] 1文ごとの予測（✓=正解）
  joy     | ✗neutral0.44 | ✓joy    0.46 | ✓joy    0.93 | 第一志望の会社から内定もらえた！
  joy     | ✗anger  0.59 | ✗anger  0.57 | ✗neutral0.75 | この前話してた本、やっと読み終わったよ
  joy     | ✓joy    1.00 | ✓joy    1.00 | ✓joy    1.00 | 久しぶりに家族でご飯に行けて楽しかった
  joy     | ✓joy    0.68 | ✓joy    0.66 | ✓joy    0.98 | ずっと悩んでた実験がやっとうまくいったんだ
  joy     | ✓joy    0.92 | ✓joy    0.93 | ✓joy    0.96 | 今日は天気が良くて気分がいいな
  sadness | ✓sadness0.94 | ✓sadness0.93 | ✓sadness0.88 | 飼ってた猫が昨日死んじゃったんだ
  sadness | ✗anger  0.56 | ✗anger  0.56 | ✓sadness0.57 | 頑張ったのに試験に落ちてしまった
  sadness | ✓sadness0.96 | ✓sadness0.96 | ✓sadness0.99 | 仲の良かった友達が遠くに引っ越しちゃう
  sadness | ✓sadness0.51 | ✓sadness0.49 | ✓sadness0.90 | 最近なんだか何をしても楽しくないんだ
  sadness | ✓sadness0.96 | ✓sadness0.96 | ✓sadness0.87 | 楽しみにしてた旅行が中止になっちゃった
  anticip | ✓anticip0.91 | ✓anticip0.91 | ✓anticip0.56 | 来週ついに新しいゲームが発売されるんだ
  anticip | ✓anticip1.00 | ✓anticip1.00 | ✓anticip1.00 | 明日の発表、どんな反応がもらえるか楽しみ
  anticip | ✗neutral0.78 | ✗neutral0.78 | ✗neutral0.96 | 週末に友達と遊園地に行く予定なんだ
  anticip | ✓anticip1.00 | ✓anticip1.00 | ✓anticip1.00 | 次の実験結果が出るのが待ち遠しい
  anticip | ✓anticip0.99 | ✓anticip0.99 | ✓anticip1.00 | 夏休みに何しようか今から考えてるんだ
  surpris | ✓surpris0.95 | ✓surpris0.95 | ✓surpris1.00 | えっ、先生が急に辞めるって本当？
  surpris | ✗neutral0.76 | ✗neutral0.76 | ✗neutral0.58 | 道を歩いてたら偶然、昔の友達にばったり会った
  surpris | ✗joy    0.54 | ✗joy    0.56 | ✓surpris0.98 | まさかあのチームが優勝するとは思わなかった
  surpris | ✓surpris0.42 | ✓surpris0.41 | ✓surpris0.36 | 起きたら外が一面の雪でびっくりした
  surpris | ✗neutral0.98 | ✗neutral0.98 | ✓surpris0.93 | 知らない番号から電話が来たと思ったら、高校の同級生だった
  anger   | ✓anger  0.94 | ✓anger  0.95 | ✓anger  1.00 | この対応は本当にひどい
  anger   | ✓anger  1.00 | ✓anger  1.00 | ✓anger  1.00 | 何度言っても約束を守らないのはどういうこと？
  anger   | ✓anger  0.97 | ✓anger  0.97 | ✓anger  0.99 | 順番抜かしされて、正直かなり頭にきた
  anger   | ✓anger  0.83 | ✓anger  0.83 | ✓anger  0.73 | 勝手に人のデータを消すなんて信じられない
  anger   | ✓anger  0.97 | ✓anger  0.97 | ✓anger  1.00 | 説明もなしに予定を変えられて腹が立つ
  fear    | ✗neutral0.62 | ✗neutral0.63 | ✓fear   0.63 | 夜道を歩いてたら、後ろからずっと足音がついてくるんだ
  fear    | ✓fear   0.69 | ✓fear   0.69 | ✗anticip0.65 | 明日の手術のことを考えると不安で眠れない
  fear    | ✓fear   0.85 | ✓fear   0.83 | ✓fear   1.00 | 大きい地震が来たらどうしようって最近よく考える
  fear    | ✓fear   1.00 | ✓fear   1.00 | ✓fear   0.89 | 締め切りに間に合わなかったらどうなるか怖い
  fear    | ✗anger  0.46 | ✗anger  0.46 | ✓fear   0.94 | さっきから部屋で変な物音がするんだけど
  disgust | ✗neutral0.98 | ✗neutral0.98 | ✓disgust0.87 | 冷蔵庫の奥から腐った弁当が出てきて最悪
  disgust | ✓disgust0.60 | ✓disgust0.61 | ✗anger  0.64 | 人の悪口ばかり言う人とは関わりたくない
  disgust | ✗neutral0.49 | ✗neutral0.51 | ✗anger  1.00 | 電車で隣の人がずっと大声で電話してて不快だった
  disgust | ✗anger  0.48 | ✗anger  0.47 | ✓disgust0.92 | 排水溝にぬめりがびっしりで気持ち悪い
  disgust | ✗fear   0.32 | ✗fear   0.33 | ✗joy    0.31 | 嘘をついて人を陥れるなんて、見ていて気分が悪くなる
  trust   | ✓trust  1.00 | ✓trust  1.00 | ✓trust  1.00 | 先輩に任せておけば大丈夫だと思ってる
  trust   | ✓trust  1.00 | ✓trust  1.00 | ✓trust  1.00 | あなたに相談すると、いつも安心できるよ
  trust   | ✓trust  1.00 | ✓trust  1.00 | ✓trust  1.00 | 彼なら約束は必ず守ってくれる
  trust   | ✓trust  0.95 | ✓trust  0.95 | ✓trust  0.99 | このお店の店長さんは本当に信頼できる人なんだ
  trust   | ✓trust  1.00 | ✓trust  1.00 | ✓trust  1.00 | 困ったときは家族がいるから心強い
  neutral | ✓neutral0.96 | ✓neutral0.96 | ✗anticip0.99 | 大学の学食について教えてください
  neutral | ✗joy    0.78 | ✗joy    0.78 | ✗joy    0.94 | こんにちは
  neutral | ✗trust  0.83 | ✗trust  0.82 | ✗joy    0.58 | こんいちは
  neutral | ✗anticip1.00 | ✗anticip1.00 | ✗anticip1.00 | 明日の天気はどうなるかな
  neutral | ✓neutral0.97 | ✓neutral0.97 | ✗anticip0.58 | 研究室の場所を教えてもらえますか
  neutral | ✓neutral0.61 | ✓neutral0.60 | ✓neutral0.71 | 今日の昼ごはん何食べた？
  （列の順: 同梱（生成条件） | 再生成（生成条件） | 理解条件）

[eval] 1文ごとの結果を保存 -> /workspace/app_labGuide_v2/backend/data/eval/results/probe_eval_20260928_071555.csv

{'summary': {'同梱（生成条件）': {'acc_all': 0.6521739130434783,
   'acc_emotion': 0.675,
   'acc_neutral': 0.5,
   'neutral_misfire': 0.5,
   'mean_true_prob': 0.6304334550555011,
   'probe_test_acc': 0.8827948910593538},
  '再生成（生成条件）': {'acc_all': 0.6739130434782609,
   'acc_emotion': 0.7,
   'acc_neutral': 0.5,
   'neutral_misfire': 0.5,
   'mean_true_prob': 0.6289858332351208,
   'probe_test_acc': 0.8827948910593538},
  '理解条件': {'acc_all': 0.7391304347826086,
   'acc_emotion': 0.825,
   'acc_neutral': 0.16666666666666666,
   'neutral_misfire': 0.8333333333333334,
   'mean_true_prob': 0.6872124708796545,
   'probe_test_acc': 0.8707738542449286}},
 'results': {'同梱（生成条件）': [{'pred': 'neutral',
    'prob': 0.44290342926979065,
    'true_prob': 0.4426365792751312,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.5940212607383728,
    'true_prob': 0.13094878196716309,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.9956291913986206,
    'true_prob': 0.9956291913986206,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.6779925227165222,
    'true_prob': 0.6779925227165222,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.9224286675453186,
    'true_prob': 0.9224286675453186,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.9355891942977905,
    'true_prob': 0.9355891942977905,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.5558944940567017,
    'true_prob': 0.43339186906814575,
    'correct': False},
   {'pred': 'sadness',
    'prob': 0.95966637134552,
    'true_prob': 0.95966637134552,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.505789577960968,
    'true_prob': 0.505789577960968,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.957672655582428,
    'true_prob': 0.957672655582428,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.9122726321220398,
    'true_prob': 0.9122726321220398,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.999923586845398,
    'true_prob': 0.999923586845398,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.7761507034301758,
    'true_prob': 0.07335595041513443,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9990261793136597,
    'true_prob': 0.9990261793136597,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.987852931022644,
    'true_prob': 0.987852931022644,
    'correct': True},
   {'pred': 'surprise',
    'prob': 0.9490847587585449,
    'true_prob': 0.9490847587585449,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.757184624671936,
    'true_prob': 0.005090897902846336,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.5448753237724304,
    'true_prob': 0.3535156846046448,
    'correct': False},
   {'pred': 'surprise',
    'prob': 0.4213356077671051,
    'true_prob': 0.4213356077671051,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.979667067527771,
    'true_prob': 0.0015460678841918707,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.9446025490760803,
    'true_prob': 0.9446025490760803,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9986461997032166,
    'true_prob': 0.9986461997032166,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9708296656608582,
    'true_prob': 0.9708296656608582,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.8257320523262024,
    'true_prob': 0.8257320523262024,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9651963114738464,
    'true_prob': 0.9651963114738464,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.6158619523048401,
    'true_prob': 0.372516393661499,
    'correct': False},
   {'pred': 'fear',
    'prob': 0.6905198693275452,
    'true_prob': 0.6905198693275452,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.8458885550498962,
    'true_prob': 0.8458885550498962,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.9990906715393066,
    'true_prob': 0.9990906715393066,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.46305105090141296,
    'true_prob': 0.19545328617095947,
    'correct': False},
   {'pred': 'neutral',
    'prob': 0.9770001173019409,
    'true_prob': 0.004766699392348528,
    'correct': False},
   {'pred': 'disgust',
    'prob': 0.5950590372085571,
    'true_prob': 0.5950590372085571,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.4933525025844574,
    'true_prob': 0.010276004672050476,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.47545167803764343,
    'true_prob': 0.39638322591781616,
    'correct': False},
   {'pred': 'fear',
    'prob': 0.3237799406051636,
    'true_prob': 0.042313311249017715,
    'correct': False},
   {'pred': 'trust',
    'prob': 0.9999051094055176,
    'true_prob': 0.9999051094055176,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9997649788856506,
    'true_prob': 0.9997649788856506,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9999513626098633,
    'true_prob': 0.9999513626098633,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9497870206832886,
    'true_prob': 0.9497870206832886,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9979660511016846,
    'true_prob': 0.9979660511016846,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.9572146534919739,
    'true_prob': 0.9572146534919739,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.7810858488082886,
    'true_prob': 0.00010613813356030732,
    'correct': False},
   {'pred': 'trust',
    'prob': 0.8284205198287964,
    'true_prob': 2.4760985979810357e-05,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9989004135131836,
    'true_prob': 0.00046268964069895446,
    'correct': False},
   {'pred': 'neutral',
    'prob': 0.9670194983482361,
    'true_prob': 0.9670194983482361,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.6057131290435791,
    'true_prob': 0.6057131290435791,
    'correct': True}],
  '再生成（生成条件）': [{'pred': 'joy',
    'prob': 0.456350177526474,
    'true_prob': 0.456350177526474,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.5665249824523926,
    'true_prob': 0.14022840559482574,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.9957905411720276,
    'true_prob': 0.9957905411720276,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.655790388584137,
    'true_prob': 0.655790388584137,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.9254491329193115,
    'true_prob': 0.9254491329193115,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.9280974864959717,
    'true_prob': 0.9280974864959717,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.5561733245849609,
    'true_prob': 0.43314531445503235,
    'correct': False},
   {'pred': 'sadness',
    'prob': 0.9576842188835144,
    'true_prob': 0.9576842188835144,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.4944516718387604,
    'true_prob': 0.4944516718387604,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.9580991268157959,
    'true_prob': 0.9580991268157959,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.9074127674102783,
    'true_prob': 0.9074127674102783,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.9999135732650757,
    'true_prob': 0.9999135732650757,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.7811362147331238,
    'true_prob': 0.06637894362211227,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9988822340965271,
    'true_prob': 0.9988822340965271,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.986628532409668,
    'true_prob': 0.986628532409668,
    'correct': True},
   {'pred': 'surprise',
    'prob': 0.9527055025100708,
    'true_prob': 0.9527055025100708,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.7590258717536926,
    'true_prob': 0.005497764330357313,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.5580773949623108,
    'true_prob': 0.34682556986808777,
    'correct': False},
   {'pred': 'surprise',
    'prob': 0.41477885842323303,
    'true_prob': 0.41477885842323303,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.9820284843444824,
    'true_prob': 0.0013947670813649893,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.9501203894615173,
    'true_prob': 0.9501203894615173,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9985861778259277,
    'true_prob': 0.9985861778259277,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9700583815574646,
    'true_prob': 0.9700583815574646,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.8275763988494873,
    'true_prob': 0.8275763988494873,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9668580293655396,
    'true_prob': 0.9668580293655396,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.6294207572937012,
    'true_prob': 0.3589640259742737,
    'correct': False},
   {'pred': 'fear',
    'prob': 0.6861472129821777,
    'true_prob': 0.6861472129821777,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.8309420943260193,
    'true_prob': 0.8309420943260193,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.9990407824516296,
    'true_prob': 0.9990407824516296,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.4605996608734131,
    'true_prob': 0.19178514182567596,
    'correct': False},
   {'pred': 'neutral',
    'prob': 0.9777148962020874,
    'true_prob': 0.004565654322504997,
    'correct': False},
   {'pred': 'disgust',
    'prob': 0.6058937311172485,
    'true_prob': 0.6058937311172485,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.5105767846107483,
    'true_prob': 0.00912761501967907,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.46817323565483093,
    'true_prob': 0.4001583158969879,
    'correct': False},
   {'pred': 'fear',
    'prob': 0.3258146643638611,
    'true_prob': 0.04269829019904137,
    'correct': False},
   {'pred': 'trust',
    'prob': 0.999893069267273,
    'true_prob': 0.999893069267273,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9997546076774597,
    'true_prob': 0.9997546076774597,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9999517202377319,
    'true_prob': 0.9999517202377319,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9464993476867676,
    'true_prob': 0.9464993476867676,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9978238344192505,
    'true_prob': 0.9978238344192505,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.9552097320556641,
    'true_prob': 0.9552097320556641,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.7752947211265564,
    'true_prob': 8.526647434337065e-05,
    'correct': False},
   {'pred': 'trust',
    'prob': 0.8175964951515198,
    'true_prob': 2.2518901459989138e-05,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9989435076713562,
    'true_prob': 0.0004412793496157974,
    'correct': False},
   {'pred': 'neutral',
    'prob': 0.9689081311225891,
    'true_prob': 0.9689081311225891,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.5967316031455994,
    'true_prob': 0.5967316031455994,
    'correct': True}],
  '理解条件': [{'pred': 'joy',
    'prob': 0.9255404472351074,
    'true_prob': 0.9255404472351074,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.7502229809761047,
    'true_prob': 0.13584035634994507,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.9961209893226624,
    'true_prob': 0.9961209893226624,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.9763613939285278,
    'true_prob': 0.9763613939285278,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.961230993270874,
    'true_prob': 0.961230993270874,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.8793541789054871,
    'true_prob': 0.8793541789054871,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.5727741122245789,
    'true_prob': 0.5727741122245789,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.9888896942138672,
    'true_prob': 0.9888896942138672,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.8969466090202332,
    'true_prob': 0.8969466090202332,
    'correct': True},
   {'pred': 'sadness',
    'prob': 0.8655999898910522,
    'true_prob': 0.8655999898910522,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.5600642561912537,
    'true_prob': 0.5600642561912537,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.9999740123748779,
    'true_prob': 0.9999740123748779,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.958104133605957,
    'true_prob': 0.03321361541748047,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9989290833473206,
    'true_prob': 0.9989290833473206,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.9991196990013123,
    'true_prob': 0.9991196990013123,
    'correct': True},
   {'pred': 'surprise',
    'prob': 0.9955392479896545,
    'true_prob': 0.9955392479896545,
    'correct': True},
   {'pred': 'neutral',
    'prob': 0.5810282230377197,
    'true_prob': 0.354292631149292,
    'correct': False},
   {'pred': 'surprise',
    'prob': 0.9805994033813477,
    'true_prob': 0.9805994033813477,
    'correct': True},
   {'pred': 'surprise',
    'prob': 0.3624672591686249,
    'true_prob': 0.3624672591686249,
    'correct': True},
   {'pred': 'surprise',
    'prob': 0.9338528513908386,
    'true_prob': 0.9338528513908386,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9997130036354065,
    'true_prob': 0.9997130036354065,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9999046325683594,
    'true_prob': 0.9999046325683594,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9940980672836304,
    'true_prob': 0.9940980672836304,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.7280435562133789,
    'true_prob': 0.7280435562133789,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.9999488592147827,
    'true_prob': 0.9999488592147827,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.6337063312530518,
    'true_prob': 0.6337063312530518,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.6530445218086243,
    'true_prob': 0.09506506472826004,
    'correct': False},
   {'pred': 'fear',
    'prob': 0.9953275918960571,
    'true_prob': 0.9953275918960571,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.8871699571609497,
    'true_prob': 0.8871699571609497,
    'correct': True},
   {'pred': 'fear',
    'prob': 0.9446025490760803,
    'true_prob': 0.9446025490760803,
    'correct': True},
   {'pred': 'disgust',
    'prob': 0.8688495755195618,
    'true_prob': 0.8688495755195618,
    'correct': True},
   {'pred': 'anger',
    'prob': 0.6377167701721191,
    'true_prob': 0.21234643459320068,
    'correct': False},
   {'pred': 'anger',
    'prob': 0.9988884329795837,
    'true_prob': 0.0006407017935998738,
    'correct': False},
   {'pred': 'disgust',
    'prob': 0.9192260503768921,
    'true_prob': 0.9192260503768921,
    'correct': True},
   {'pred': 'joy',
    'prob': 0.3072473108768463,
    'true_prob': 0.01704373024404049,
    'correct': False},
   {'pred': 'trust',
    'prob': 0.9997069239616394,
    'true_prob': 0.9997069239616394,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9982424974441528,
    'true_prob': 0.9982424974441528,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9999997615814209,
    'true_prob': 0.9999997615814209,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9888794422149658,
    'true_prob': 0.9888794422149658,
    'correct': True},
   {'pred': 'trust',
    'prob': 0.9961975812911987,
    'true_prob': 0.9961975812911987,
    'correct': True},
   {'pred': 'anticipation',
    'prob': 0.985069215297699,
    'true_prob': 0.002680683508515358,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.9405329823493958,
    'true_prob': 0.0015304868575185537,
    'correct': False},
   {'pred': 'joy',
    'prob': 0.5839194059371948,
    'true_prob': 0.003579036332666874,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.9997348189353943,
    'true_prob': 1.3532111324821017e-06,
    'correct': False},
   {'pred': 'anticipation',
    'prob': 0.5802130103111267,
    'true_prob': 0.20190948247909546,
    'correct': False},
   {'pred': 'neutral',
    'prob': 0.7066494822502136,
    'true_prob': 0.7066494822502136,
    'correct': True}]},
 'items': [{'text': '第一志望の会社から内定もらえた！', 'label': 'joy'},
  {'text': 'この前話してた本、やっと読み終わったよ', 'label': 'joy', 'note': '以前 anger と誤判定された文'},
  {'text': '久しぶりに家族でご飯に行けて楽しかった', 'label': 'joy'},
  {'text': 'ずっと悩んでた実験がやっとうまくいったんだ', 'label': 'joy'},
  {'text': '今日は天気が良くて気分がいいな', 'label': 'joy'},
  {'text': '飼ってた猫が昨日死んじゃったんだ', 'label': 'sadness'},
  {'text': '頑張ったのに試験に落ちてしまった', 'label': 'sadness'},
  {'text': '仲の良かった友達が遠くに引っ越しちゃう', 'label': 'sadness'},
  {'text': '最近なんだか何をしても楽しくないんだ', 'label': 'sadness'},
  {'text': '楽しみにしてた旅行が中止になっちゃった', 'label': 'sadness'},
  {'text': '来週ついに新しいゲームが発売されるんだ', 'label': 'anticipation'},
  {'text': '明日の発表、どんな反応がもらえるか楽しみ', 'label': 'anticipation'},
  {'text': '週末に友達と遊園地に行く予定なんだ', 'label': 'anticipation'},
  {'text': '次の実験結果が出るのが待ち遠しい', 'label': 'anticipation'},
  {'text': '夏休みに何しようか今から考えてるんだ', 'label': 'anticipation'},
  {'text': 'えっ、先生が急に辞めるって本当？', 'label': 'surprise'},
  {'text': '道を歩いてたら偶然、昔の友達にばったり会った', 'label': 'surprise'},
  {'text': 'まさかあのチームが優勝するとは思わなかった', 'label': 'surprise'},
  {'text': '起きたら外が一面の雪でびっくりした', 'label': 'surprise'},
  {'text': '知らない番号から電話が来たと思ったら、高校の同級生だった', 'label': 'surprise'},
  {'text': 'この対応は本当にひどい', 'label': 'anger'},
  {'text': '何度言っても約束を守らないのはどういうこと？', 'label': 'anger'},
  {'text': '順番抜かしされて、正直かなり頭にきた', 'label': 'anger'},
  {'text': '勝手に人のデータを消すなんて信じられない', 'label': 'anger'},
  {'text': '説明もなしに予定を変えられて腹が立つ', 'label': 'anger'},
  {'text': '夜道を歩いてたら、後ろからずっと足音がついてくるんだ', 'label': 'fear'},
  {'text': '明日の手術のことを考えると不安で眠れない', 'label': 'fear'},
  {'text': '大きい地震が来たらどうしようって最近よく考える', 'label': 'fear'},
  {'text': '締め切りに間に合わなかったらどうなるか怖い', 'label': 'fear'},
  {'text': 'さっきから部屋で変な物音がするんだけど', 'label': 'fear'},
  {'text': '冷蔵庫の奥から腐った弁当が出てきて最悪', 'label': 'disgust'},
  {'text': '人の悪口ばかり言う人とは関わりたくない', 'label': 'disgust'},
  {'text': '電車で隣の人がずっと大声で電話してて不快だった', 'label': 'disgust'},
  {'text': '排水溝にぬめりがびっしりで気持ち悪い', 'label': 'disgust'},
  {'text': '嘘をついて人を陥れるなんて、見ていて気分が悪くなる', 'label': 'disgust'},
  {'text': '先輩に任せておけば大丈夫だと思ってる', 'label': 'trust'},
  {'text': 'あなたに相談すると、いつも安心できるよ', 'label': 'trust'},
  {'text': '彼なら約束は必ず守ってくれる', 'label': 'trust'},
  {'text': 'このお店の店長さんは本当に信頼できる人なんだ', 'label': 'trust'},
  {'text': '困ったときは家族がいるから心強い', 'label': 'trust'},
  {'text': '大学の学食について教えてください',
   'label': 'neutral',
   'note': 'DeBERTa が fear 0.55 と誤判定した文'},
  {'text': 'こんにちは', 'label': 'neutral'},
  {'text': 'こんいちは', 'label': 'neutral', 'note': '誤字。以前 trust 0.83 に変わった文'},
  {'text': '明日の天気はどうなるかな', 'label': 'neutral'},
  {'text': '研究室の場所を教えてもらえますか', 'label': 'neutral'},
  {'text': '今日の昼ごはん何食べた？', 'label': 'neutral'}]}

In [ ]:
# E. 比較結果の集計（D が保存した CSV から計算する。数字の出どころを残すためのセル）
import glob
import pandas as pd

csv_path = sorted(glob.glob("data/eval/results/probe_eval_*.csv"))[-1]   # 最新の結果
df = pd.read_csv(csv_path, encoding="utf-8-sig")
names = [c[:-len(":pred")] for c in df.columns if c.endswith(":pred")]   # プローブの表示名
is_neu = df["label"] == "neutral"
print("集計に使ったCSV:", csv_path)

# (1) 感情文・中立文ごとの正解数と正解率
rows = []
for nm in names:
    ok = df[f"{nm}:correct"] == 1
    rows.append({"プローブ": nm,
                 "感情文": f"{ok[~is_neu].sum()}/{(~is_neu).sum()}", "感情文 正解率": round(ok[~is_neu].mean(), 3),
                 "中立文": f"{ok[is_neu].sum()}/{is_neu.sum()}",   "中立文 正解率": round(ok[is_neu].mean(), 3),
                 "全体 正解率": round(ok.mean(), 3)})
display(pd.DataFrame(rows))

# (2) 中立文を各プローブがどう判定したか（理解条件が質問を anticipation と読む傾向の確認）
display(df.loc[is_neu, ["text"] + [f"{nm}:pred" for nm in names]])

# (3) 最初と最後のプローブで、正誤が分かれた文
a, b = names[0], names[-1]
diff = df[df[f"{a}:correct"] != df[f"{b}:correct"]]
print(f"正誤が分かれた文: {len(diff)}件（{a} と {b}）")
display(diff[["text", "label", f"{a}:pred", f"{b}:pred"]])

集計に使ったCSV: data/eval/results/probe_eval_20260928_071555.csv

        プローブ    感情文  感情文 正解率  中立文  中立文 正解率  全体 正解率
0   同梱（生成条件）  27/40    0.675  3/6    0.500   0.652
1  再生成（生成条件）  28/40    0.700  3/6    0.500   0.674
2       理解条件  33/40    0.825  1/6    0.167   0.739

                text 同梱（生成条件）:pred 再生成（生成条件）:pred     理解条件:pred
40  大学の学食について教えてください       neutral        neutral  anticipation
41             こんにちは           joy            joy           joy
42             こんいちは         trust          trust           joy
43      明日の天気はどうなるかな  anticipation   anticipation  anticipation
44  研究室の場所を教えてもらえますか       neutral        neutral  anticipation
45      今日の昼ごはん何食べた？       neutral        neutral       neutral

正誤が分かれた文: 12件（同梱（生成条件） と 理解条件）

                            text     label 同梱（生成条件）:pred     理解条件:pred
0               第一志望の会社から内定もらえた！       joy       neutral           joy
6               頑張ったのに試験に落ちてしまった   sadness         anger       sadness
17         まさかあのチームが優勝するとは思わなかった  surprise           joy      surprise
19  知らない番号から電話が来たと思ったら、高校の同級生だった  surprise       neutral      surprise
25    夜道を歩いてたら、後ろからずっと足音がついてくるんだ      fear       neutral          fear
26          明日の手術のことを考えると不安で眠れない      fear          fear  anticipation
29           さっきから部屋で変な物音がするんだけど      fear         anger          fear
30           冷蔵庫の奥から腐った弁当が出てきて最悪   disgust       neutral       disgust
31           人の悪口ばかり言う人とは関わりたくない   disgust       disgust         anger
33            排水溝にぬめりがびっしりで気持ち悪い   disgust         anger       disgust
40              大学の学食について教えてください   neutral       neutral  anticipation
44              研究室の場所を教えてもらえますか   neutral       neutral  anticipation

In [ ]:
# F. 大まかな方向の評価（感情の正負・プルチックの環での近さ）
#    アプリは確率ベクトル全体を内部状態に足すので、1位の正誤だけでなく「どの方向に傾いたか」も評価する
import numpy as np
import pandas as pd
from app.core.emotion_probe import EmotionProbe
from scripts.evaluate_probes import load_eval_set

# プルチックの環の順（45°ずつ並ぶ。EmotionDynamics と同じ順序）
WHEEL = ["joy", "trust", "fear", "surprise", "sadness", "disgust", "anger", "anticipation"]
# 感情の正負（前提: anticipation は正、surprise は正負どちらでもない 0 とした）
VALENCE = {"joy": +1, "trust": +1, "anticipation": +1, "surprise": 0,
           "fear": -1, "sadness": -1, "disgust": -1, "anger": -1}
# 環上の単位ベクトル（joy を 0°として45°ずつ）
U = {e: np.array([np.cos(2 * np.pi * i / 8), np.sin(2 * np.pi * i / 8)]) for i, e in enumerate(WHEEL)}

probes = {
    "生成条件（同梱）": "data/processed/steering_assets/emotion_probe/probe_layer21.npz",
    "理解条件": "/tmp/rebuilt_pl/emotion_probe/probe_layer21.npz",
}
items = load_eval_set()
records = []
for name, path in probes.items():
    probe = EmotionProbe(WHEEL, engine, probe_path=path)
    for it in items:
        p = dict(zip(WHEEL, probe.predict_emotion(it["text"])))   # neutral を除く8感情の確率
        vec = sum(p[e] * U[e] for e in WHEEL)                     # 予測を環上の1点にまとめる
        val = sum(p[e] * VALENCE[e] for e in WHEEL)               # 正負の傾き（+なら正、-なら負）
        rec = {"probe": name, "text": it["text"], "label": it["label"],
               "neutral_prob": probe.neutral_score(it["text"]), "valence": val}
        if it["label"] != "neutral":
            # 環コサイン: 予測の方向と正解の方向の cos（1=一致, 0.71=隣, 0=90°ずれ, -1=反対）
            rec["wheel_cos"] = float(vec @ U[it["label"]] / (np.linalg.norm(vec) + 1e-12))
            v = VALENCE[it["label"]]
            # 正負一致: 正解の正負がある文（surprise 以外）だけ判定する
            rec["valence_ok"] = float(np.sign(val) == v) if v != 0 else np.nan
        records.append(rec)
df_dir = pd.DataFrame(records)

# 集計（感情文40件。中立文は neutral 確率の平均だけ見る）
emo = df_dir[df_dir["label"] != "neutral"]
summary = emo.groupby("probe").agg(
    環コサイン平均=("wheel_cos", "mean"),
    隣接まで許容した正解率=("wheel_cos", lambda s: (s >= 0.7).mean()),   # cos45° ≒ 0.71
    正負一致率=("valence_ok", "mean"))                                   # surprise の文は除外される
summary["中立文のneutral確率平均"] = df_dir[df_dir["label"] == "neutral"].groupby("probe")["neutral_prob"].mean()
display(summary.round(3))

# 1文ごとの環コサイン（どの文が大きく外れたか）
display(emo.pivot_table(index=["label", "text"], columns="probe", values="wheel_cos").round(2))
df_dir.to_csv("data/eval/results/probe_eval_direction.csv", index=False, encoding="utf-8-sig")

[eval] 評価セット 46件 読み込み: /workspace/app_labGuide_v2/backend/data/eval/probe_eval_set.jsonl
[eval] ラベルごとの件数: {'anger': 5, 'anticipation': 5, 'disgust': 5, 'fear': 5, 'joy': 5, 'neutral': 6, 'sadness': 5, 'surprise': 5, 'trust': 5}
[EmotionProbe] data/processed/steering_assets/emotion_probe/probe_layer21.npz を読み込みました (layer=21, dataset=synthetic_resp, position=response_mean, test_acc=0.883, classes=9)
[EmotionProbe] /tmp/rebuilt_pl/emotion_probe/probe_layer21.npz を読み込みました (layer=21, dataset=synthetic_promptlast, position=prompt_last, test_acc=0.871, classes=9)

          環コサイン平均  隣接まで許容した正解率  正負一致率  中立文のneutral確率平均
probe
理解条件        0.897        0.950  0.943            0.153
生成条件（同梱）    0.802        0.825  0.971            0.422

probe                                      理解条件  生成条件（同梱）
label        text
anger        この対応は本当にひどい                   1.00      1.00
             何度言っても約束を守らないのはどういうこと？        1.00      1.00
             勝手に人のデータを消すなんて信じられない          1.00      1.00
             説明もなしに予定を変えられて腹が立つ            1.00      1.00
             順番抜かしされて、正直かなり頭にきた            1.00      1.00
anticipation 夏休みに何しようか今から考えてるんだ            1.00      1.00
             明日の発表、どんな反応がもらえるか楽しみ          1.00      1.00
             来週ついに新しいゲームが発売されるんだ           0.94      1.00
             次の実験結果が出るのが待ち遠しい              1.00      1.00
             週末に友達と遊園地に行く予定なんだ             0.99      0.86
disgust      人の悪口ばかり言う人とは関わりたくない           0.86      0.97
             冷蔵庫の奥から腐った弁当が出てきて最悪           1.00      0.65
             嘘をついて人を陥れるなんて、見ていて気分が悪くなる    -0.39      0.57
             排水溝にぬめりがびっしりで気持ち悪い            1.00      0.93
             電車で隣の人がずっと大声で電話してて不快だった       0.71      0.72
fear         さっきから部屋で変な物音がするんだけど           1.00     -1.00
             夜道を歩いてたら、後ろからずっと足音がついてくるんだ    1.00      1.00
             大きい地震が来たらどうしようって最近よく考える       1.00      0.99
             明日の手術のことを考えると不安で眠れない         -0.79      0.95
             締め切りに間に合わなかったらどうなるか怖い         1.00      1.00
joy          この前話してた本、やっと読み終わったよ           0.99      0.20
             ずっと悩んでた実験がやっとうまくいったんだ         1.00      1.00
             久しぶりに家族でご飯に行けて楽しかった           1.00      1.00
             今日は天気が良くて気分がいいな               1.00      1.00
             第一志望の会社から内定もらえた！              1.00      1.00
sadness      仲の良かった友達が遠くに引っ越しちゃう           1.00      1.00
             最近なんだか何をしても楽しくないんだ            1.00      0.75
             楽しみにしてた旅行が中止になっちゃった           0.99      1.00
             頑張ったのに試験に落ちてしまった              0.80      0.62
             飼ってた猫が昨日死んじゃったんだ              1.00      1.00
surprise     えっ、先生が急に辞めるって本当？              1.00      1.00
             まさかあのチームが優勝するとは思わなかった         1.00     -0.15
             知らない番号から電話が来たと思ったら、高校の同級生だった  1.00      0.87
             起きたら外が一面の雪でびっくりした             0.81      1.00
             道を歩いてたら偶然、昔の友達にばったり会った        0.99     -0.82
trust        あなたに相談すると、いつも安心できるよ           1.00      1.00
             このお店の店長さんは本当に信頼できる人なんだ        1.00      1.00
             先輩に任せておけば大丈夫だと思ってる            1.00      1.00
             困ったときは家族がいるから心強い              1.00      1.00
             彼なら約束は必ず守ってくれる                1.00      1.00